"""alter volunteer_schedules route nullable add available_time

Revision ID: 3289b011bcb8
Revises: a1680722ffc9
Create Date: 2026-04-13 22:51:26.539959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3289b011bcb8'
down_revision: Union[str, None] = 'a1680722ffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_schedules', sa.Column('available_time', sa.String(length=5), nullable=True))
    op.alter_column('volunteer_schedules', 'route',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_schedules', 'route',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)
    op.drop_column('volunteer_schedules', 'available_time')
    # ### end Alembic commands ###
