"""init

Revision ID: 7bcf77ff8439
Revises: 
Create Date: 2026-04-09 14:17:51.878524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bcf77ff8439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('shelter', 'volunteer', 'admin', name='user_role'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'suspended', 'banned', name='account_status_enum'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('rest_area', 'train', 'bus', 'shelter', name='waypoint_type_enum'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waypoints_geom', 'waypoints', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('push_subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uq_push_subscriptions_user_endpoint')
    )
    op.create_table('shelter_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('shelter_registration_doc_url', sa.String(length=500), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transport_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shelter_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('recruiting', 'in_transit', 'completed', 'cancelled', name='post_status_enum'), server_default='recruiting', nullable=False),
    sa.Column('animal_name', sa.String(length=50), nullable=False),
    sa.Column('animal_size', sa.Enum('small', 'medium', 'large', name='animal_size_post_enum'), nullable=False),
    sa.Column('animal_photo_url', sa.String(length=500), nullable=True),
    sa.Column('animal_notes', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('share_token', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_transport_posts_status_scheduled_date', 'transport_posts', ['status', 'scheduled_date'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_animal_size', sa.Enum('small', 'medium', 'large', name='animal_size_enum'), nullable=False),
    sa.Column('activity_regions', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transport_post_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'push', name='notification_channel_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status_enum'), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transport_post_id'], ['transport_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('relay_chains',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transport_post_id', sa.BigInteger(), nullable=False),
    sa.Column('backup_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'active', 'completed', 'broken', name='chain_status_enum'), server_default='proposed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transport_post_id'], ['transport_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relay_chains_transport_post_id', 'relay_chains', ['transport_post_id'], unique=False)
    op.create_table('volunteer_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('route_description', sa.Text(), nullable=False),
    sa.Column('route', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('available_date', sa.Date(), nullable=False),
    sa.Column('origin_area', sa.String(length=100), nullable=False),
    sa.Column('destination_area', sa.String(length=100), nullable=False),
    sa.Column('vehicle_available', sa.Boolean(), nullable=False),
    sa.Column('max_animal_size', sa.Enum('small', 'medium', 'large', name='animal_size_schedule_enum'), nullable=False),
    sa.Column('status', sa.Enum('available', 'matched', 'expired', name='schedule_status_enum'), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['transport_posts.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_volunteer_schedules_available_date_status', 'volunteer_schedules', ['available_date', 'status'], unique=False)
    op.create_index('ix_volunteer_schedules_route', 'volunteer_schedules', ['route'], unique=False, postgresql_using='gist')
    op.create_index('ix_volunteer_schedules_volunteer_id', 'volunteer_schedules', ['volunteer_id'], unique=False)
    op.create_table('relay_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_order', sa.SmallInteger(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_code', sa.CHAR(length=6), nullable=True),
    sa.Column('handover_code_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_code_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_method', sa.Enum('code', 'manual_approval', name='handover_method_enum'), nullable=True),
    sa.Column('ping_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ping_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'in_progress', 'completed', 'needs_verification', 'no_show', name='segment_status_enum'), server_default='pending', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['relay_chains.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relay_segments_chain_id', 'relay_segments', ['chain_id'], unique=False)
    op.create_index('ix_relay_segments_volunteer_id_status', 'relay_segments', ['volunteer_id', 'status'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('departure', 'waypoint', 'arrival', name='checkpoint_type_enum'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['relay_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkpoints_segment_id', 'checkpoints', ['segment_id'], unique=False)
    op.create_table('volunteer_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['relay_segments.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_history')
    op.drop_index('ix_checkpoints_segment_id', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_relay_segments_volunteer_id_status', table_name='relay_segments')
    op.drop_index('ix_relay_segments_chain_id', table_name='relay_segments')
    op.drop_table('relay_segments')
    op.drop_index('ix_volunteer_schedules_volunteer_id', table_name='volunteer_schedules')
    op.drop_index('ix_volunteer_schedules_route', table_name='volunteer_schedules', postgresql_using='gist')
    op.drop_index('ix_volunteer_schedules_available_date_status', table_name='volunteer_schedules')
    op.drop_table('volunteer_schedules')
    op.drop_index('ix_relay_chains_transport_post_id', table_name='relay_chains')
    op.drop_table('relay_chains')
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('volunteer_profiles')
    op.drop_index('ix_transport_posts_status_scheduled_date', table_name='transport_posts')
    op.drop_table('transport_posts')
    op.drop_table('shelter_profiles')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_waypoints_geom', table_name='waypoints', postgresql_using='gist')
    op.drop_table('waypoints')
    op.drop_table('users')
    # ### end Alembic commands ###
