"""alter volunteer_profiles max_animal_size nullable

Revision ID: a1680722ffc9
Revises: 7bcf77ff8439
Create Date: 2026-04-10 00:01:11.133372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1680722ffc9'
down_revision: Union[str, None] = '7bcf77ff8439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_profiles', 'max_animal_size',
               existing_type=postgresql.ENUM('small', 'medium', 'large', name='animal_size_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_profiles', 'max_animal_size',
               existing_type=postgresql.ENUM('small', 'medium', 'large', name='animal_size_enum'),
               nullable=False)
    # ### end Alembic commands ###
