"""add_push_subscriptions_table

Revision ID: d856dcdf8f32
Revises: 4fcd2a6fff38
Create Date: 2026-05-12 20:59:04.934017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd856dcdf8f32'
down_revision: Union[str, None] = '4fcd2a6fff38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_relay_segments_waypoint_id'), 'relay_segments', type_='foreignkey')
    op.create_foreign_key(None, 'relay_segments', 'waypoints', ['waypoint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relay_segments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_relay_segments_waypoint_id'), 'relay_segments', 'waypoints', ['waypoint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
